import Foundation

struct MobileInterviewGuideSummary: Identifiable, Hashable, Sendable {
    let company: String
    let slug: String
    let stageCount: Int
    let questionCount: Int
    let difficulty: Double?
    var id: String { slug }
}

enum MobileInterviewGuideCatalog {
    static let companies = 301
    static let questions = 22611
    static let stages = 821

    static let all: [MobileInterviewGuideSummary] = [
        .init(company: "1Password", slug: "1password-interview-guide", stageCount: 0, questionCount: 78, difficulty: 6.0),
        .init(company: "23andMe", slug: "23andme-interview-guide", stageCount: 12, questionCount: 77, difficulty: 6.0),
        .init(company: "Adobe", slug: "adobe", stageCount: 2, questionCount: 77, difficulty: 6.0),
        .init(company: "Adyen", slug: "adyen-interview-guide", stageCount: 1, questionCount: 78, difficulty: 7.0),
        .init(company: "Affirm", slug: "affirm-interview-guide", stageCount: 4, questionCount: 78, difficulty: 7.0),
        .init(company: "Airbnb", slug: "airbnb", stageCount: 5, questionCount: 77, difficulty: 7.0),
        .init(company: "Airbyte", slug: "airbyte-interview-guide", stageCount: 1, questionCount: 77, difficulty: 6.0),
        .init(company: "Airtable", slug: "airtable-interview-guide", stageCount: 10, questionCount: 78, difficulty: 7.0),
        .init(company: "Akamai", slug: "akamai-interview-guide", stageCount: 1, questionCount: 77, difficulty: 7.0),
        .init(company: "Akuna Capital", slug: "akuna-capital-interview-guide", stageCount: 0, questionCount: 77, difficulty: 8.0),
        .init(company: "Algolia", slug: "algolia-interview-guide", stageCount: 1, questionCount: 77, difficulty: 6.0),
        .init(company: "Alibaba", slug: "alibaba-interview-guide", stageCount: 13, questionCount: 77, difficulty: 7.0),
        .init(company: "Amazon", slug: "amazon", stageCount: 4, questionCount: 77, difficulty: 7.0),
        .init(company: "AMD", slug: "amd-interview-guide", stageCount: 4, questionCount: 77, difficulty: 6.0),
        .init(company: "American Express", slug: "american-express-interview-guide", stageCount: 1, questionCount: 77, difficulty: 6.0),
        .init(company: "Amplitude", slug: "amplitude-interview-guide", stageCount: 1, questionCount: 77, difficulty: 6.0),
        .init(company: "Anduril", slug: "anduril-interview-guide", stageCount: 4, questionCount: 77, difficulty: 7.0),
        .init(company: "Anthropic", slug: "anthropic", stageCount: 6, questionCount: 77, difficulty: 8.5),
        .init(company: "Anyscale", slug: "anyscale-interview-guide", stageCount: 0, questionCount: 77, difficulty: 7.0),
        .init(company: "Apollo.io", slug: "apollo-io-interview-guide", stageCount: 1, questionCount: 77, difficulty: 6.0),
        .init(company: "Apple", slug: "apple", stageCount: 4, questionCount: 79, difficulty: 8.0),
        .init(company: "Apple Silicon", slug: "apple-silicon-team-interview-guide", stageCount: 12, questionCount: 75, difficulty: 8.5),
        .init(company: "AppLovin", slug: "applovin-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.5),
        .init(company: "AQR Capital Management", slug: "aqr-capital-management-interview-guide", stageCount: 5, questionCount: 75, difficulty: 8.0),
        .init(company: "Asana", slug: "asana", stageCount: 3, questionCount: 77, difficulty: 7.5),
        .init(company: "Astronomer", slug: "astronomer-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.5),
        .init(company: "Atlassian", slug: "atlassian", stageCount: 2, questionCount: 77, difficulty: 7.0),
        .init(company: "Bank of America", slug: "bank-of-america-bofa-securities-interview-guide", stageCount: 0, questionCount: 75, difficulty: 5.5),
        .init(company: "Beehiiv", slug: "beehiiv-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "BigCommerce", slug: "bigcommerce-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Black Forest Labs", slug: "black-forest-labs-interview-guide", stageCount: 1, questionCount: 75, difficulty: 8.5),
        .init(company: "BlackRock", slug: "blackrock-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.5),
        .init(company: "Blizzard/Activision", slug: "blizzard-activision-interview-guide", stageCount: 17, questionCount: 75, difficulty: 7.0),
        .init(company: "Block", slug: "block", stageCount: 2, questionCount: 77, difficulty: 7.5),
        .init(company: "Bloomberg", slug: "bloomberg", stageCount: 3, questionCount: 75, difficulty: 7.5),
        .init(company: "Blue Origin", slug: "blue-origin-interview-guide", stageCount: 13, questionCount: 75, difficulty: 7.0),
        .init(company: "Bluesky", slug: "bluesky-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Booking.com", slug: "booking-com-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.5),
        .init(company: "Box", slug: "box-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Braze", slug: "braze-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Brex", slug: "brex", stageCount: 3, questionCount: 78, difficulty: 7.5),
        .init(company: "Bridgewater Associates", slug: "bridgewater-associates-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Broadcom", slug: "broadcom-interview-guide", stageCount: 4, questionCount: 74, difficulty: 6.5),
        .init(company: "Bumble", slug: "bumble-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "ByteDance/TikTok", slug: "bytedance-tiktok-interview-guide", stageCount: 4, questionCount: 75, difficulty: 8.0),
        .init(company: "Calm", slug: "calm-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Canva", slug: "canva", stageCount: 2, questionCount: 76, difficulty: 7.0),
        .init(company: "Capital One", slug: "capital-one-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.5),
        .init(company: "CarGurus", slug: "cargurus-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Carta", slug: "carta-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.5),
        .init(company: "Carvana", slug: "carvana-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.5),
        .init(company: "Character.AI", slug: "character-ai-interview-guide", stageCount: 13, questionCount: 75, difficulty: 7.5),
        .init(company: "Chime", slug: "chime", stageCount: 2, questionCount: 78, difficulty: 7.0),
        .init(company: "Chronosphere", slug: "chronosphere-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Circle/Ripple/Chainalysis", slug: "crypto-trio-circle-ripple-chainalysis-interview-guide", stageCount: 0, questionCount: 74, difficulty: 7.0),
        .init(company: "CircleCI", slug: "circleci-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Cisco", slug: "cisco", stageCount: 15, questionCount: 77, difficulty: 6.5),
        .init(company: "Citadel Hedge Fund", slug: "citadel-hedge-fund-interview-guide", stageCount: 0, questionCount: 74, difficulty: 8.0),
        .init(company: "Citadel Securities", slug: "citadel-securities", stageCount: 4, questionCount: 75, difficulty: 8.5),
        .init(company: "Citi", slug: "citi-interview-guide", stageCount: 4, questionCount: 74, difficulty: 6.0),
        .init(company: "Clerk", slug: "clerk-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.5),
        .init(company: "ClickHouse", slug: "clickhouse-interview-guide", stageCount: 0, questionCount: 75, difficulty: 8.0),
        .init(company: "ClickUp", slug: "clickup-interview-guide", stageCount: 10, questionCount: 74, difficulty: 6.0),
        .init(company: "Cloudera", slug: "cloudera-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Cloudflare", slug: "cloudflare", stageCount: 3, questionCount: 73, difficulty: 7.5),
        .init(company: "Cockroach Labs", slug: "cockroach-labs-interview-guide", stageCount: 0, questionCount: 75, difficulty: 8.0),
        .init(company: "Coda", slug: "coda-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Codecademy", slug: "codecademy-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "CodeSandbox", slug: "codesandbox-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Cohere", slug: "cohere", stageCount: 2, questionCount: 74, difficulty: 7.5),
        .init(company: "Coinbase", slug: "coinbase", stageCount: 2, questionCount: 74, difficulty: 7.5),
        .init(company: "Confluent", slug: "confluent-interview-guide", stageCount: 13, questionCount: 74, difficulty: 7.0),
        .init(company: "ConvertKit", slug: "convertkit-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "CoreWeave", slug: "coreweave-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Coursera", slug: "coursera-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Credit Karma", slug: "credit-karma-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Cribl", slug: "cribl-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "CrowdStrike", slug: "crowdstrike-interview-guide", stageCount: 4, questionCount: 74, difficulty: 7.0),
        .init(company: "Cursor", slug: "cursor", stageCount: 2, questionCount: 74, difficulty: 8.0),
        .init(company: "D. E. Shaw", slug: "de-shaw", stageCount: 2, questionCount: 76, difficulty: 9.0),
        .init(company: "Databricks", slug: "databricks", stageCount: 4, questionCount: 74, difficulty: 8.0),
        .init(company: "Datadog", slug: "datadog", stageCount: 3, questionCount: 76, difficulty: 8.0),
        .init(company: "DataStax", slug: "datastax-interview-guide", stageCount: 0, questionCount: 76, difficulty: 7.0),
        .init(company: "dbt Labs", slug: "dbt-labs-interview-guide", stageCount: 1, questionCount: 76, difficulty: 6.0),
        .init(company: "Decagon", slug: "decagon-interview-guide", stageCount: 0, questionCount: 76, difficulty: 7.0),
        .init(company: "Deel", slug: "deel", stageCount: 2, questionCount: 76, difficulty: 7.0),
        .init(company: "Deepgram", slug: "deepgram-interview-guide", stageCount: 1, questionCount: 76, difficulty: 7.0),
        .init(company: "Defense Primes", slug: "defense-primes-lockheed-northrop-raytheon-interview-guide", stageCount: 12, questionCount: 76, difficulty: 6.0),
        .init(company: "Deutsche Bank", slug: "deutsche-bank-interview-guide", stageCount: 4, questionCount: 76, difficulty: 6.0),
        .init(company: "Discord", slug: "discord", stageCount: 2, questionCount: 76, difficulty: 7.5),
        .init(company: "DocuSign", slug: "docusign", stageCount: 2, questionCount: 76, difficulty: 6.5),
        .init(company: "Doppler", slug: "doppler-interview-guide", stageCount: 1, questionCount: 76, difficulty: 6.0),
        .init(company: "Drata", slug: "drata-interview-guide", stageCount: 1, questionCount: 76, difficulty: 6.0),
        .init(company: "Dropbox", slug: "dropbox-interview-guide", stageCount: 1, questionCount: 76, difficulty: 7.0),
        .init(company: "DRW", slug: "drw-interview-guide", stageCount: 0, questionCount: 76, difficulty: 8.0),
        .init(company: "DuckDB Labs", slug: "duckdb-labs-interview-guide", stageCount: 1, questionCount: 76, difficulty: 8.0),
        .init(company: "Duolingo", slug: "duolingo-interview-guide", stageCount: 1, questionCount: 76, difficulty: 6.5),
        .init(company: "Elastic", slug: "elastic-interview-guide", stageCount: 13, questionCount: 76, difficulty: 7.0),
        .init(company: "Electronic Arts", slug: "electronic-arts-ea-interview-guide", stageCount: 16, questionCount: 76, difficulty: 6.0),
        .init(company: "ElevenLabs", slug: "elevenlabs-interview-guide", stageCount: 1, questionCount: 76, difficulty: 7.0),
        .init(company: "Epic Games", slug: "epic-games-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Epic Systems", slug: "epic-systems-interview-guide", stageCount: 9, questionCount: 74, difficulty: 6.0),
        .init(company: "Etsy", slug: "etsy-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Eventbrite", slug: "eventbrite-interview-guide", stageCount: 1, questionCount: 75, difficulty: 5.0),
        .init(company: "Evercore", slug: "evercore-interview-guide", stageCount: 4, questionCount: 74, difficulty: 6.0),
        .init(company: "Faire", slug: "faire-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Fastly", slug: "fastly-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Fidelity Investments", slug: "fidelity-investments-interview-guide", stageCount: 4, questionCount: 74, difficulty: 5.0),
        .init(company: "Figma", slug: "figma", stageCount: 2, questionCount: 76, difficulty: 8.0),
        .init(company: "Fireworks AI", slug: "fireworks-ai", stageCount: 2, questionCount: 78, difficulty: 8.5),
        .init(company: "Five9", slug: "five9-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "Fivetran", slug: "fivetran-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Flow Traders", slug: "flow-traders-interview-guide", stageCount: 5, questionCount: 75, difficulty: 8.0),
        .init(company: "Fly.io", slug: "fly-io-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Framer", slug: "framer-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Gainsight", slug: "gainsight-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "Galaxy Digital", slug: "galaxy-digital-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "GitLab", slug: "gitlab", stageCount: 4, questionCount: 76, difficulty: 7.0),
        .init(company: "Glassdoor", slug: "glassdoor-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "Glean", slug: "glean-interview-guide", stageCount: 13, questionCount: 75, difficulty: 7.0),
        .init(company: "Goldman Sachs", slug: "goldman-sachs-strats-engineering-interview-guide", stageCount: 0, questionCount: 75, difficulty: 8.0),
        .init(company: "Gong", slug: "gong-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Google", slug: "google", stageCount: 3, questionCount: 75, difficulty: 9.0),
        .init(company: "Grab", slug: "grab-interview-guide", stageCount: 12, questionCount: 74, difficulty: 7.0),
        .init(company: "Grafana Labs", slug: "grafana-labs-interview-guide", stageCount: 0, questionCount: 74, difficulty: 7.0),
        .init(company: "Greenhouse", slug: "greenhouse-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "Grubhub", slug: "grubhub-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Gusto", slug: "gusto-interview-guide", stageCount: 0, questionCount: 74, difficulty: 6.0),
        .init(company: "HackerRank", slug: "hackerrank-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Harvey", slug: "harvey-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "HashiCorp", slug: "hashicorp", stageCount: 2, questionCount: 75, difficulty: 8.0),
        .init(company: "Headspace", slug: "headspace-interview-guide", stageCount: 1, questionCount: 74, difficulty: 5.0),
        .init(company: "Heroku", slug: "heroku-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Hex", slug: "hex", stageCount: 2, questionCount: 74, difficulty: 7.5),
        .init(company: "Hightouch", slug: "hightouch-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "Hippocratic AI", slug: "hippocratic-ai-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Honeycomb", slug: "honeycomb-interview-guide", stageCount: 1, questionCount: 74, difficulty: 7.0),
        .init(company: "Hopper", slug: "hopper-interview-guide", stageCount: 1, questionCount: 74, difficulty: 6.0),
        .init(company: "HubSpot", slug: "hubspot", stageCount: 3, questionCount: 74, difficulty: 6.5),
        .init(company: "Hudson River Trading", slug: "hudson-river-trading", stageCount: 2, questionCount: 75, difficulty: 9.0),
        .init(company: "Hugging Face", slug: "hugging-face-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "IMC Trading", slug: "imc-trading-interview-guide", stageCount: 0, questionCount: 75, difficulty: 8.0),
        .init(company: "Indeed", slug: "indeed-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Instacart", slug: "instacart-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Intel", slug: "intel-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Intercom", slug: "intercom-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Iterable", slug: "iterable-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Jane Street", slug: "jane-street", stageCount: 2, questionCount: 75, difficulty: 9.0),
        .init(company: "JetBrains", slug: "jetbrains-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "JPMorgan Chase", slug: "jpmorgan-tech-quant-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Jump Trading", slug: "jump-trading", stageCount: 2, questionCount: 75, difficulty: 9.0),
        .init(company: "Klarna", slug: "klarna-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Klaviyo", slug: "klaviyo-interview-guide", stageCount: 0, questionCount: 75, difficulty: 6.0),
        .init(company: "Kraken", slug: "kraken-interview-guide", stageCount: 5, questionCount: 75, difficulty: 6.0),
        .init(company: "Lambda Labs", slug: "lambda-labs-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "LangChain", slug: "langchain", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Lattice", slug: "lattice-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "LaunchDarkly", slug: "launchdarkly-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Lazard", slug: "lazard-interview-guide", stageCount: 8, questionCount: 75, difficulty: 6.0),
        .init(company: "LeetCode", slug: "leetcode-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Lightspeed Commerce", slug: "lightspeed-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Linear", slug: "linear", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "LinkedIn", slug: "linkedin", stageCount: 3, questionCount: 75, difficulty: 8.0),
        .init(company: "LlamaIndex", slug: "llamaindex-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Lyft", slug: "lyft-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Mailchimp", slug: "mailchimp-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Man Group", slug: "man-group-interview-guide", stageCount: 5, questionCount: 75, difficulty: 7.0),
        .init(company: "Marqeta", slug: "marqeta-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Match Group", slug: "match-group-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Materialize", slug: "materialize-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Medium", slug: "medium-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Mercury", slug: "mercury", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Meta", slug: "meta-facebook", stageCount: 3, questionCount: 75, difficulty: 9.0),
        .init(company: "Microsoft", slug: "microsoft", stageCount: 4, questionCount: 75, difficulty: 8.0),
        .init(company: "Millennium Management", slug: "millennium-management-interview-guide", stageCount: 0, questionCount: 75, difficulty: 8.0),
        .init(company: "Mistral AI", slug: "mistral-ai-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Mixpanel", slug: "mixpanel-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Modal", slug: "modal", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Monday.com", slug: "monday-com-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "MongoDB", slug: "mongodb", stageCount: 2, questionCount: 75, difficulty: 8.0),
        .init(company: "Morgan Stanley", slug: "morgan-stanley-tech-quant-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "MotherDuck", slug: "motherduck", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Neon", slug: "neon", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Netflix", slug: "netflix", stageCount: 3, questionCount: 75, difficulty: 8.0),
        .init(company: "New Relic", slug: "new-relic-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Niantic", slug: "niantic-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Notion", slug: "notion", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Nvidia", slug: "nvidia", stageCount: 3, questionCount: 75, difficulty: 8.0),
        .init(company: "Okta", slug: "okta-interview-guide", stageCount: 13, questionCount: 75, difficulty: 6.0),
        .init(company: "OpenAI", slug: "openai", stageCount: 3, questionCount: 75, difficulty: 9.0),
        .init(company: "Opendoor", slug: "opendoor-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Optiver", slug: "optiver-interview-guide", stageCount: 7, questionCount: 75, difficulty: 8.0),
        .init(company: "Oracle", slug: "oracle-interview", stageCount: 1, questionCount: 75, difficulty: 8.0),
        .init(company: "Orca Security", slug: "orca-security-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Outreach", slug: "outreach-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "PagerDuty", slug: "pagerduty-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Palantir", slug: "palantir", stageCount: 5, questionCount: 75, difficulty: 8.0),
        .init(company: "Palo Alto Networks", slug: "palo-alto-networks-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Patreon", slug: "patreon-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "PayPal", slug: "paypal", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Peloton", slug: "peloton-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Pendo", slug: "pendo-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Perplexity", slug: "perplexity", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Pika Labs", slug: "pika-labs-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Pinecone", slug: "pinecone-interview-guide", stageCount: 14, questionCount: 75, difficulty: 7.0),
        .init(company: "Pinterest", slug: "pinterest-interview", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Plaid", slug: "plaid", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "PlanetScale", slug: "planetscale", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Point72", slug: "point72-interview-guide", stageCount: 0, questionCount: 75, difficulty: 9.0),
        .init(company: "PostHog", slug: "posthog-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Postman", slug: "postman", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Procore", slug: "procore-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Pulumi", slug: "pulumi-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Qdrant", slug: "qdrant-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Qualcomm", slug: "qualcomm-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Quora", slug: "quora-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Ramp", slug: "ramp", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Rapid7", slug: "rapid7-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Reddit", slug: "reddit-interview", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Redfin", slug: "redfin-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Reka AI", slug: "reka-ai-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Renaissance Technologies", slug: "renaissance-technologies-interview-guide", stageCount: 0, questionCount: 75, difficulty: 9.0),
        .init(company: "Render", slug: "render-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Replicate", slug: "replicate", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Replit", slug: "replit-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Resend", slug: "resend-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Retool", slug: "retool", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "RingCentral", slug: "ringcentral-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Riot Games", slug: "riot-games-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Rippling", slug: "rippling", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Robinhood", slug: "robinhood", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Roblox", slug: "roblox", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Rubrik", slug: "rubrik-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "RunPod", slug: "runpod-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Runway", slug: "runway-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Sakana AI", slug: "sakana-ai-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Salesforce", slug: "salesforce", stageCount: 5, questionCount: 75, difficulty: 8.0),
        .init(company: "Salesloft", slug: "salesloft-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Samsung", slug: "samsung-electronics-interview-guide", stageCount: 3, questionCount: 75, difficulty: 7.0),
        .init(company: "SAP", slug: "sap", stageCount: 19, questionCount: 75, difficulty: 8.0),
        .init(company: "Scale AI", slug: "scale-ai", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "SentinelOne", slug: "sentinelone-interview-guide", stageCount: 13, questionCount: 75, difficulty: 7.0),
        .init(company: "Sentry", slug: "sentry-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "ServiceNow", slug: "servicenow", stageCount: 2, questionCount: 75, difficulty: 8.0),
        .init(company: "Shopify", slug: "shopify", stageCount: 14, questionCount: 75, difficulty: 6.0),
        .init(company: "Sierra", slug: "sierra-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "SIG Susquehanna", slug: "sig-susquehanna-interview-guide", stageCount: 8, questionCount: 75, difficulty: 9.0),
        .init(company: "SingleStore", slug: "singlestore-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Skyscanner", slug: "skyscanner-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Smartsheet", slug: "smartsheet-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Snap", slug: "snap", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Snowflake", slug: "snowflake", stageCount: 2, questionCount: 75, difficulty: 8.0),
        .init(company: "Snyk", slug: "snyk-interview-guide", stageCount: 11, questionCount: 75, difficulty: 7.0),
        .init(company: "SoFi", slug: "sofi-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Sony", slug: "sony-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "SoundCloud", slug: "soundcloud-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Sourcegraph", slug: "sourcegraph", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "SpaceX", slug: "spacex-interview-guide", stageCount: 13, questionCount: 75, difficulty: 8.0),
        .init(company: "Splunk", slug: "splunk-interview-guide", stageCount: 13, questionCount: 75, difficulty: 7.0),
        .init(company: "Spotify", slug: "spotify", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Squarespace", slug: "squarespace-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Stability AI", slug: "stability-ai-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "State Street", slug: "state-street-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Stripe", slug: "stripe", stageCount: 4, questionCount: 75, difficulty: 8.0),
        .init(company: "Substack", slug: "substack-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Suno", slug: "suno-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Supabase", slug: "supabase", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Sysdig", slug: "sysdig-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Tailscale", slug: "tailscale", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "Temporal", slug: "temporal-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Tempus AI", slug: "tempus-ai-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Tesla", slug: "tesla", stageCount: 3, questionCount: 75, difficulty: 7.0),
        .init(company: "Toast", slug: "toast-interview-guide", stageCount: 0, questionCount: 75, difficulty: 6.0),
        .init(company: "Together AI", slug: "together-ai", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Tower Research Capital", slug: "tower-research-capital-interview-guide", stageCount: 0, questionCount: 75, difficulty: 9.0),
        .init(company: "Turso", slug: "turso", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Twilio", slug: "twilio-interview-guide", stageCount: 0, questionCount: 75, difficulty: 6.0),
        .init(company: "Two Sigma", slug: "two-sigma", stageCount: 2, questionCount: 75, difficulty: 9.0),
        .init(company: "Uber", slug: "uber", stageCount: 3, questionCount: 75, difficulty: 6.0),
        .init(company: "UBS", slug: "ubs-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Unity", slug: "unity-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Vanguard", slug: "vanguard-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Veeva Systems", slug: "veeva-systems-interview-guide", stageCount: 4, questionCount: 75, difficulty: 6.0),
        .init(company: "Vercel", slug: "vercel", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "Virtu Financial", slug: "virtu-financial-interview-guide", stageCount: 0, questionCount: 75, difficulty: 9.0),
        .init(company: "Wealthfront", slug: "wealthfront", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "Weaviate", slug: "weaviate-interview-guide", stageCount: 10, questionCount: 75, difficulty: 7.0),
        .init(company: "Webflow", slug: "webflow-interview-guide", stageCount: 1, questionCount: 75, difficulty: 7.0),
        .init(company: "Wells Fargo", slug: "wells-fargo-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Wintermute", slug: "wintermute-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
        .init(company: "Wise", slug: "wise-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Workday", slug: "workday", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "WorkOS", slug: "workos-interview-guide", stageCount: 0, questionCount: 75, difficulty: 7.0),
        .init(company: "xAI", slug: "xai", stageCount: 2, questionCount: 75, difficulty: 7.0),
        .init(company: "XTX Markets", slug: "xtx-markets-interview-guide", stageCount: 5, questionCount: 75, difficulty: 8.0),
        .init(company: "Yelp", slug: "yelp-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Zendesk", slug: "zendesk-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Zillow", slug: "zillow-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Zoom", slug: "zoom", stageCount: 2, questionCount: 75, difficulty: 6.0),
        .init(company: "ZoomInfo", slug: "zoominfo-interview-guide", stageCount: 1, questionCount: 75, difficulty: 6.0),
        .init(company: "Zscaler", slug: "zscaler-interview-guide", stageCount: 4, questionCount: 75, difficulty: 7.0),
    ]

    static var featured: [MobileInterviewGuideSummary] {
        all.sorted { left, right in
            let leftScore = left.questionCount * 4 + left.stageCount * 2 + Int(left.difficulty ?? 0)
            let rightScore = right.questionCount * 4 + right.stageCount * 2 + Int(right.difficulty ?? 0)
            return leftScore == rightScore ? left.company < right.company : leftScore > rightScore
        }
    }

    /// Mirrors the first company cards shown on the web Interview Studio.
    /// The complete catalog is still available through search and categories.
    static var webFeatured: [MobileInterviewGuideSummary] {
        let slugs = [
            "sap", "figma", "scale-ai", "hashicorp", "mercury", "vercel",
            "alibaba-interview-guide", "okta-interview-guide", "spacex-interview-guide",
            "confluent-interview-guide", "openai", "wealthfront"
        ]
        let bySlug = Dictionary(uniqueKeysWithValues: all.map { ($0.slug, $0) })
        return slugs.compactMap { bySlug[$0] }
    }

    static func topicChips(for slug: String) -> [String] {
        featuredContent[slug]?.topics ?? []
    }

    static func tipCount(for slug: String) -> Int {
        featuredContent[slug]?.tips ?? 0
    }

    private static let featuredContent: [String: (topics: [String], tips: Int)] = [
        "sap": (["API design and implementation", "Database query optimization"], 22),
        "figma": (["Implement a data structure tied to a practical operation", "Parse or transform a structured stream"], 11),
        "scale-ai": (["Data processing with quality constraints", "Fuzzy matching or deduplication"], 11),
        "hashicorp": (["Implement a small primitive with specific semantics", "Parse a structured wire format"], 11),
        "mercury": (["Model a transfer lifecycle with all failure paths", "Implement an idempotent processor"], 11),
        "vercel": (["Build a small stateful component or hook", "Parse or transform a structured stream"], 11),
        "alibaba-interview-guide": ([], 7),
        "okta-interview-guide": ([], 7),
        "spacex-interview-guide": ([], 7),
        "confluent-interview-guide": ([], 6),
        "openai": (["Implement a specific data structure to meet tight complexity", "Streaming / parsing problems"], 17),
        "wealthfront": (["Tax-lot matching", "Rebalancing optimization"], 11),
    ]
}
